// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(MaintenanceDbContext))]
    [Migration("20260610201020_FlattenResourceModel")]
    partial class FlattenResourceModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.types.Airplane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Airplanes");
                });

            modelBuilder.Entity("backend.types.MaintenanceOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("backend.types.MaintenanceSite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CurrentTaskId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTaskId");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("backend.types.MaintenanceTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AirplaneId")
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<DateTimeOffset>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaintenanceOrderId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AirplaneId");

                    b.HasIndex("MaintenanceOrderId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("backend.types.Personnel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CurrentOrderId")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrentTaskId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CurrentOrderId");

                    b.HasIndex("CurrentTaskId");

                    b.ToTable("Personnel");
                });

            modelBuilder.Entity("backend.types.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AirplaneId")
                        .HasColumnType("integer");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AirplaneId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.HasIndex("Name", "Type")
                        .IsUnique();

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("backend.types.TaskResourceRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<int>("ResourceId")
                        .HasColumnType("integer");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("TaskId");

                    b.ToTable("ResourceRequirements");
                });

            modelBuilder.Entity("backend.types.MaintenanceSite", b =>
                {
                    b.HasOne("backend.types.MaintenanceTask", "CurrentTask")
                        .WithMany()
                        .HasForeignKey("CurrentTaskId");

                    b.Navigation("CurrentTask");
                });

            modelBuilder.Entity("backend.types.MaintenanceTask", b =>
                {
                    b.HasOne("backend.types.Airplane", "Airplane")
                        .WithMany()
                        .HasForeignKey("AirplaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.types.MaintenanceOrder", "MaintenanceOrder")
                        .WithMany("Tasks")
                        .HasForeignKey("MaintenanceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airplane");

                    b.Navigation("MaintenanceOrder");
                });

            modelBuilder.Entity("backend.types.Personnel", b =>
                {
                    b.HasOne("backend.types.MaintenanceOrder", "CurrentOrder")
                        .WithMany()
                        .HasForeignKey("CurrentOrderId");

                    b.HasOne("backend.types.MaintenanceTask", "CurrentTask")
                        .WithMany("AssignedPersonnel")
                        .HasForeignKey("CurrentTaskId");

                    b.Navigation("CurrentOrder");

                    b.Navigation("CurrentTask");
                });

            modelBuilder.Entity("backend.types.Resource", b =>
                {
                    b.HasOne("backend.types.Airplane", null)
                        .WithMany("Resources")
                        .HasForeignKey("AirplaneId");
                });

            modelBuilder.Entity("backend.types.TaskResourceRequirement", b =>
                {
                    b.HasOne("backend.types.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.types.MaintenanceTask", "Task")
                        .WithMany("ResourceRequirements")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("backend.types.ResourceBuffer", "Buffer", b1 =>
                        {
                            b1.Property<int>("TaskResourceRequirementId")
                                .HasColumnType("integer");

                            b1.Property<int>("MaxReqAmount")
                                .HasColumnType("integer");

                            b1.Property<int>("MinReqAmount")
                                .HasColumnType("integer");

                            b1.Property<int>("OptimalReqAmount")
                                .HasColumnType("integer");

                            b1.HasKey("TaskResourceRequirementId");

                            b1.ToTable("ResourceRequirements");

                            b1.WithOwner()
                                .HasForeignKey("TaskResourceRequirementId");
                        });

                    b.Navigation("Buffer")
                        .IsRequired();

                    b.Navigation("Resource");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("backend.types.Airplane", b =>
                {
                    b.Navigation("Resources");
                });

            modelBuilder.Entity("backend.types.MaintenanceOrder", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("backend.types.MaintenanceTask", b =>
                {
                    b.Navigation("AssignedPersonnel");

                    b.Navigation("ResourceRequirements");
                });
#pragma warning restore 612, 618
        }
    }
}
